### ISSUE TITLE
Tag & release 0.8

### ISSUE THREAD

**Issue by groovecoder** [jbalogh/jingo#67] opened 2015-04-07 12:21 UTC
The master branch has [an important fix for Django 1.7](https://github.com/jbalogh/jingo/commit/fce09043542e71d972cc97d2ae703740741f80d0).

It's worth a tag & a release to PyPI.

**Comment by jsocol** [comment] 2015-04-07 12:27
Give me two weeks and let me fix the |f regression in 0.7. 

--

**Comment by jezdez** [comment] 2015-05-08 15:43
Mind doing that release for us?

**Comment by jsocol** [comment] 2015-05-08 16:08
Yes, I do.

Sorry, I know this is a pain point for y'all and I know I'm way behind schedule, but I'm not cutting a release with the `|f` regression in here.

I will do my very best to make time to do it today. Life and day job have not given me a lot of FLOSS time lately.

**Comment by jezdez** [comment] 2015-05-08 17:09
@jsocol Understood, really. We may need to look into adopting the package (or another renderer) since frankly I know too well how being a dependency on a bigger partner (and/or old employer) can suck the fun out of FLOSS.

**Comment by davedash** [comment] 2015-05-08 17:32
I ran into this with other projects.

I'd suggest mozilla making their own pypi package and putting it in their
own mirror rather than being dependent on a OSS maintainer's schedule.

I have had awesome luck with devpi and similar projects and would be happy
to advise.

**Comment by jezdez** [comment] 2015-05-08 17:58
@davedash Agreed fully, devpi or some other type of custom index makes sense to me, except there is a lack of organization in the Python projects ever since the first guard left the company. Then webdev got shattered and made coordinated maintenance or even a common policy impossible. So in other words, no way in hell something like devpi will be adopted in practice.

**Comment by jsocol** [comment] 2015-05-08 18:16
OK, this is what's happening:

Per discussion in #53 #54 and #59 (now merged), the next release is 0.7.1. It reverts the behavior of `|f` to what it was before 0.7. I'm not adding anything else, beyond what's already in master. Assuming travis passes, which is taking its sweet time.

I'm also going to try to do v0.8 today. That will, at least, include #70 and the change to deprecate (via deprecation warning) `|f` entirely, in favor of `|fe`.

**Comment by groovecoder** [comment] 2015-07-13 17:50
@jsocol - any chance to get back to this yet? And/or could we put this under some official Mozilla maintenance to get staff time on it?

**Comment by jsocol** [comment] 2015-09-21 18:08
I talked about this with @jezdez in IRC, but here's what I'm sort of proposing with #74:

- master moves on to v0.8, and drops support for Django <1.7, including the 1.4 LTS.
- I created a branch [v0.7.x](https://github.com/jbalogh/jingo/tree/v0.7.x) from the current master and is just there in case there's anything we want to backport.

**Comment by jsocol** [comment] 2015-10-19 17:43
@groovecoder @jezdez any chance one of you could take a look at #74 this week?

**Comment by jsocol** [comment] 2015-10-20 12:48
https://pypi.python.org/pypi/jingo/0.8 is up on PyPI. It fixes Django 1.7/1.8, but drops support for 1.6 and 1.4ESR.

**Closed by jsocol** 2015-10-20 12:48 UTC
