### ISSUE TITLE
Please release a new version to PyPI

### ISSUE THREAD

**Issue by bobsilverberg** [jbalogh/jingo#64] opened 2015-01-21 02:25 UTC
There have been some patches added to jingo that are not in version 0.7.
Would it be possible to do a release?

**Comment by peterbe** [comment] 2015-01-21 17:26
ping @jsocol since I think you can do releases on this project too, right?

**Comment by jsocol** [comment] 2015-01-21 17:35
Yeah I'm the primary maintainer. I'll take a look this week. Number, I think, #71 still needs to be fixed and has some comments. (A regression in the behavior of |f, whichever PR that is.)

--

**Comment by peterbe** [comment] 2015-01-21 18:03
Number #71?

**Comment by jsocol** [comment] 2015-01-21 21:07
Oh and of course it doesn't even link issues when you comment via email. It's #59. Number #59. Number No. #59.

**Comment by mythmon** [comment] 2015-02-19 01:13
It seems #59 is almost ready to go. With Django 1.8 looming on the horizon, it's becoming more and more important to have a release of Jingo that support Django 1.7 (Before 1.6 is deprecated). Any chance of this getting fixed soon?

**Comment by jsocol** [comment] 2015-09-21 18:09
Closing this in favor of #67, and the fact that 0.7.1 is out.

**Closed by jsocol** 2015-09-21 18:09 UTC
